### ISSUE TITLE
Cloudflare permissions using API tokens

### ISSUE THREAD

**Issue by net47** [cert-manager/website#200] opened 2020-05-04 15:14 UTC
Following up to https://github.com/jetstack/cert-manager/issues/2878, the API token permissions listed at https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/ seems to be wrong. Can you tell me what permissions are needed for the usage of API tokens?

Thanks!

**Comment by sidapa** [comment] 2020-05-14 03:01
seems like you just need to put the the secret in the cert-manager namespace like:

```
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
...

```

**Comment by net47** [comment] 2020-05-14 07:05
I now put the secret into the cert-manager namespace, but: 
```
28s         Warning   PresentError              challenge/testo123.tremmel.xyz-4279057665-3231985707-1063803102   Error presenting challenge: error getting cloudflare secret: secret "cloudflare-api-token-secret" not found
```
-> which is quite clear because the certificate fetching is done via an other namespace than `cert-manager`, basically where you have your ingress resources etc. (in my case just the `default`namespace)

**Comment by kz12123** [comment] 2020-06-03 14:11
Ran into something similar, nothing seemed to work except drain, reboot, uncordon the k8s node.

Bonkers if I know whats going on with k8s or what's broken but the golden rule of reboot from the legacy world* still works wonders.

**Comment by WoLpH** [comment] 2020-06-17 08:38
I've currently given these permissions including "All Zones from an account" and it's still not working:
![image](https://user-images.githubusercontent.com/270571/84875438-451f3200-b086-11ea-9e83-5c94c8b66530.png)


Error:
```
Cloudflare API Error
Error: 0: Actor 'com.cloudflare.api.token....' requires permission 'com.cloudflare.api.account.zone.list' to list zones
```

I've used the permissions as suggested by one of the people in this topic: https://community.cloudflare.com/t/bug-zone-detail-by-name-requires-zone-list-permission/128042

**Comment by mzac** [comment] 2020-06-17 15:18
Same problem here... Been trying for a few days to figure this out...

**Comment by WoLpH** [comment] 2020-06-17 15:23
I found that you can work around the issue by choosing "All Zones". But that's a _really_ suboptimal solution since I've got many zones under my account.

**Comment by net47** [comment] 2020-06-17 16:17
Since I anyhow migrated my stuff to GCP, I also migrated DNS - and everything works like a charm. So there‘s either an error in the CF hook in cert-manager or CF itself changed something, because this was definitely working before with the exact same settings.

Maybe someone from the cert-manager team can reproduce this error?

**Comment by WoLpH** [comment] 2020-06-17 20:52
@net47 the CF team definitely changed something, take a look at this link for a discussion: https://community.cloudflare.com/t/bug-zone-detail-by-name-requires-zone-list-permission/128042

It does appear like it's something that the cert-manager team needs to fix though.

**Comment by keslerm** [comment] 2020-06-19 22:12
Also running into this. I've every permission suggested and none of them work.

Seems to me that something is broken.

**Comment by mitsumaui** [comment] 2020-07-08 07:51
+1 here for also having the same problem. Agree that it seems like some adjustments in cert-manager is required. Seems like the original issue needs to be re-opened.

**Comment by meyskens** [comment] 2020-07-16 11:47
cert-manager 0.16.0-alpha.1+ will list more information on the error, it seems a permission denied error could be caused by issues with the DNS nameserves. More info is at https://github.com/jetstack/cert-manager/issues/3083#issuecomment-659221132 
If you can try this out (especially once 0.16 alpha 1 is out) and report back in that issue that will help us a lot, thanks!

**Comment by meyskens** [comment] 2020-08-04 14:06
Going to close this. Feel free to reopen if needed.

/close

**Closed by meyskens** 2020-08-04 14:06 UTC
