### ISSUE TITLE
OpenShift - broken link

### ISSUE THREAD

**Issue by absynth76** [cert-manager/website#486] opened 2021-03-26 10:45 UTC
on page https://cert-manager.io/docs/installation/openshift/#installing-with-cert-manager-operator
in text "On OpenShift 4 you can also install cert-manager via the OperatorHub using the cert-manager operator"

the link towards redhat portal is broken

**Comment by rursprung** [comment] 2021-05-03 14:58
i just came across the same issue. what's more: even when i search for the operator on the openshift page i don't find it. is it possible that this isn't just a broken link but a bit more: that the operator isn't available at all (anymore)?
is it still a viable option to use an operator for this on openshift or do we need to deploy it manually?

**Comment by coriaedu** [comment] 2021-05-20 23:51
I had the same issue. So having no instructions on running `cert-manager` with the operator, I followed what I thought was the right thing and ended up with somewhat messy `openshift-operators` namespace.

1. Installed the `cert-manager` operator with OperatorHub
2. Created an instance of **CertManager** using the _Form View_
    * Because the `cert-manager` namespace was never created, the **CertManager** instance defaults to `openshift-operators` namespace.

I ended up with `cert-manager` deployed in `openshift-operators` along with corresponding secrets and such...

**Comment by maelvls** [comment] 2021-05-21 16:01
I think I created a duplicate of this in https://github.com/cert-manager/website/issues/556. I'll close my other issue.

**Comment by maelvls** [comment] 2021-05-25 08:52
We chatted a bit about this broken link this morning, and Matt found a link to a "Container Application":
> https://catalog.redhat.com/software/containers/jetstack/cert-manager-controller/5e9999b769aea31642b60fef

@mattbates How do I find the link to the OpenShift Operator listing for cert-manager to fix the dead link?

**Comment by inteon** [comment] 2021-07-29 22:14
@maelvls looks like this issue is fixed? I think @wallrj fixed this in #626?

**Closed** 2024-08-29 09:14 UTC
